### ISSUE TITLE
markdown with file ?

### ISSUE THREAD

**Issue by SheepDomination** [satokaz/vscode-memo-life-for-you#33]
What about an option to save the markdown file with the file ?

**Comment by satokaz** [comment]
@SheepDomination 

Please tell me in for me to understand correctly.
What kind of specific options are you seeking?

**Comment by SheepDomination** [comment]
The extension Marginalia can save the markdown note with the file, although it doesn't work as claimed; but that is what I'd to see with the extension, memo-life-for-you.
