### ISSUE TITLE
open with 'Markdown Preview Enhanced'

### ISSUE THREAD

**Issue by okhide** [satokaz/vscode-memo-life-for-you#36]
Currently, it looks that it can preview markdown files with 'Markdown Preview Enhance'(MPE).
However, it cannot open the files with MPE(just, can open with default preview feature).
I appreciate if it is available features to open files with MPE.

**Comment by satokaz** [comment]
@okhide 

Thanks for the suggestion.
Please wait for 0.4.8 release.

#37

**Comment by satokaz** [comment]
@okhide 
Published 0.4.8 to the marketplace.

**Comment by okhide** [comment]
Thank you so much for your prompt support.
I've just checked the new feature and found it was just what I needed.

Thank you.
