### ISSUE TITLE
edit/list: support other file-extensions

### ISSUE THREAD

**Issue by kkneutgen** [satokaz/vscode-memo-life-for-you#43]
"Memo: List/Edit" filters files by .md-extension. Other files in .config/memo/_posts/ are ignored.

It would be great if valid file-extensions could be configured.

**Comment by satokaz** [comment]
@kkneutgen 

I'm sorry to have kept you waiting.
The following options have been added.

#52 feat: Issue #43. Added memo-life-for-you.listDisplayExtname setting to allow customizable listed file extensions. 

* The files to be displayed in the list have only `.md` and `.txt` extensions (default). Can be changed in the `memo-life-for-you.listDisplayExtname` setting.

    ```jsonc
        "memo-life-for-you.listDisplayExtname": [
            "md",
            "txt"
        ],
    ```

Add the extension of the file you want to include.
The default has been changed to `md` (.md) and `txt` (.txt).
